# Generated by Django 5.1.4 on 2026-07-18 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, help_text='Full datetime of when the show begins (timezone-aware).', verbose_name='Start Time')),
                ('end_time', models.DateTimeField(help_text='Set automatically based on start_time + movie.duration_minutes.', verbose_name='End Time (calculated)')),
                ('date', models.DateField(db_index=True, help_text='Denormalised date for efficient date-based filtering without truncating datetime.', verbose_name='Show Date')),
                ('language', models.CharField(help_text='Override language (e.g. dubbed version differs from movie.language).', max_length=50, verbose_name='Language')),
                ('format', models.CharField(blank=True, default='2D', help_text='Screen format, e.g. "2D", "IMAX", "4DX", "PXL", "LUXE".', max_length=50, verbose_name='Format')),
                ('is_cancellable', models.BooleanField(default=True, help_text='Whether this show allows ticket cancellation.', verbose_name='Cancellation Allowed')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='movies.movie', verbose_name='Movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='theaters.screen', verbose_name='Screen')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked (in checkout)'), ('BOOKED', 'Booked')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('locked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Locked At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_show_seats', to=settings.AUTH_USER_MODEL, verbose_name='Locked By')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='show_seats', to='theaters.seat', verbose_name='Seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='shows.show', verbose_name='Show')),
            ],
            options={
                'verbose_name': 'Show Seat',
                'verbose_name_plural': 'Show Seats',
            },
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['movie', 'date', 'is_active'], name='shows_show_movie_i_1ff73b_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['screen', 'date'], name='shows_show_screen__c73d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['date', 'is_active'], name='shows_show_date_6d903a_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'status'], name='shows_shows_show_id_154d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['locked_at', 'status'], name='shows_shows_locked__b8f59c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showseat',
            unique_together={('show', 'seat')},
        ),
    ]
