# Generated by Django 5.1.4 on 2026-07-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='City Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL Slug')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='State')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive cities are hidden from the city selector.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Screen 1", "IMAX", "Screen A"', max_length=100, verbose_name='Screen Name')),
                ('total_capacity', models.PositiveIntegerField(default=0, help_text='Auto-computed when seats are added; can be set manually.', verbose_name='Total Seat Capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
                'ordering': ['theater', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CLASSIC', 'Classic'), ('PREMIUM', 'Premium'), ('RECLINER', 'Recliner')], max_length=20, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Indian Rupees.', max_digits=8, verbose_name='Price (INR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_categories', to='theaters.screen', verbose_name='Screen')),
            ],
            options={
                'verbose_name': 'Seat Category',
                'verbose_name_plural': 'Seat Categories',
                'unique_together': {('screen', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Theater Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='e.g. ["Parking", "Food Court", "Wheelchair Access"]', verbose_name='Amenities')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theaters', to='theaters.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Theater',
                'verbose_name_plural': 'Theaters',
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.theater', verbose_name='Theater'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(help_text='Row identifier, e.g. "A", "B", "AA"', max_length=5, verbose_name='Row')),
                ('seat_number', models.PositiveSmallIntegerField(verbose_name='Seat Number')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive seats are hidden from the seat map (e.g., broken/reserved).', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.screen', verbose_name='Screen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='theaters.seatcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['screen', 'row_label', 'seat_number'],
                'indexes': [models.Index(fields=['screen', 'is_active'], name='theaters_se_screen__e63021_idx')],
                'unique_together': {('screen', 'row_label', 'seat_number')},
            },
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['city', 'is_active'], name='theaters_th_city_id_014a38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('theater', 'name')},
        ),
    ]
