# Generated by Django 5.1.4 on 2026-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Genre Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Synopsis')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Runtime in minutes. Must be > 0.', verbose_name='Duration (minutes)')),
                ('language', models.CharField(db_index=True, max_length=50, verbose_name='Language')),
                ('release_date', models.DateField(db_index=True, verbose_name='Release Date')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poster Image')),
                ('trailer_url', models.URLField(blank=True, default='', help_text='YouTube embed URL or similar.', verbose_name='Trailer URL')),
                ('cast_info', models.JSONField(blank=True, default=list, help_text='List of {"name": "...", "role": "...", "image": "..."} objects.', verbose_name='Cast Information')),
                ('rating', models.CharField(choices=[('U', 'U — Universal'), ('UA', 'UA — Parental Guidance'), ('A', 'A — Adults Only'), ('S', 'S — Special Audience')], default='UA', max_length=5, verbose_name='Rating')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive movies are hidden from the public listing.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-release_date'],
                'indexes': [models.Index(fields=['language', 'is_active'], name='movies_movi_languag_497475_idx'), models.Index(fields=['release_date', 'is_active'], name='movies_movi_release_32c060_idx')],
            },
        ),
    ]
