# Generated by Django 5.1.4 on 2026-07-18 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_url',
            field=models.URLField(blank=True, null=True, verbose_name='Backdrop URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True, verbose_name='Poster URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDb ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Trailer URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default='', help_text='Legacy YouTube embed URL or similar.', verbose_name='Trailer URL'),
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Actor Name')),
                ('character_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Character Name')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Photo URL')),
                ('tmdb_person_id', models.IntegerField(blank=True, null=True, verbose_name='TMDb Person ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='movies.movie', verbose_name='Movie')),
            ],
            options={
                'verbose_name': 'Cast Member',
                'verbose_name_plural': 'Cast Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
