# Generated by Django 5.1.4 on 2026-07-18 06:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public-facing unique reference shown to the customer.', unique=True, verbose_name='Booking Reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired (lock timed out)')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Amount (INR)')),
                ('payment_ref', models.CharField(blank=True, default='', help_text='Reference from the (mock) payment gateway.', max_length=255, verbose_name='Payment Reference')),
                ('booked_at', models.DateTimeField(blank=True, help_text='Set when the booking is confirmed (after successful payment).', null=True, verbose_name='Booked At')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='shows.show', verbose_name='Show')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='Snapshot of seat price at booking time — price may change later.', max_digits=8, verbose_name='Price at Time of Booking (INR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='bookings.booking', verbose_name='Booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_seats', to='theaters.seat', verbose_name='Seat')),
                ('show_seat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking_seat', to='shows.showseat', verbose_name='Show Seat')),
            ],
            options={
                'verbose_name': 'Booking Seat',
                'verbose_name_plural': 'Booking Seats',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show', 'status'], name='bookings_bo_show_id_d9a7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_ref'], name='bookings_bo_booking_c0d7c7_idx'),
        ),
    ]
